### PR TITLE
added background animation

### PR DESCRIPTION
**Pull request by HridoyHazard**
added background animation according the weather condition

### CODE REVIEW

**Comment by ShivamWho** [comment]
it has no animation when the weather is Clouds
Screenshot 2022-10-09 195449

**Comment by HridoyHazard** [comment]
wait let me fix it

**Comment by ShivamWho** [comment]
Clouds video buffers a lot

**Comment by HridoyHazard** [comment]
@ShivamWho  can you check plz. used lite sized animation

**Pull request merged**
